# Generated by Django 6.1.1 on 2026-10-10 14:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="phone_number",
            field=core.fields.PhoneField(blank=True, max_length=20, null=True),
        ),
    ]
