# Generated by Django 6.1.1 on 2026-10-10 14:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ngo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngoprofile",
            name="description",
            field=core.fields.FreeTextField(
                blank=True,
                default="",
                label="Description",
                min_length=30,
                rule_max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="official_phone",
            field=core.fields.PhoneField(max_length=20),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="organization_name",
            field=core.fields.OrganisationNameField(
                label="Organisation name", max_length=200, rule_max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="registering_authority",
            field=core.fields.OrganisationNameField(
                label="Registering authority", max_length=200, rule_max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="registration_number",
            field=core.fields.IdentifierField(
                label="Registration number", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="website",
            field=core.fields.HttpsUrlField(
                blank=True, default="", label="Website", max_length=200
            ),
        ),
    ]
