// ============================================================
// MindCare — Therapist Console: Weekly Report
// ============================================================

import React, { useState } from 'react';
import { useParams, Navigate } from 'react-router-dom';
import { LineChart, Line, ResponsiveContainer, XAxis, Tooltip } from 'recharts';
import { Download, Send, Pencil } from 'lucide-react';
import TherapistLayout from '../components/therapist/TherapistLayout';
import Sparkline from '../components/therapist/Sparkline';
import { LAYLA_WEEKLY_REPORT, CONSOLE_ROUTES } from '../constants/therapistConsole';
import { sanitizeText, MAX_LENGTHS } from '../utils/validation';

const INSIGHT_STYLES: Record<string, string> = {
  positive: 'border-emerald-500',
  warning: 'border-amber-500',
  negative: 'border-red-500',
};

const WeeklyReportPage: React.FC = () => {
  const { patientId } = useParams<{ patientId: string }>();
  const report = LAYLA_WEEKLY_REPORT;
  const [note, setNote] = useState(report.noteToPatient);
  const [editingNote, setEditingNote] = useState(false);
  const [sent, setSent] = useState(false);

  if (patientId && patientId !== report.patientId) {
    // Only Layla's report is fully authored for this demo.
    return <Navigate to={CONSOLE_ROUTES.PATIENTS} replace />;
  }

  const moodChartData = report.moodDaily.map((d) => ({ ...d }));

  const handleApproveAndSend = () => {
    // TODO: real API call — must independently re-check that this
    // therapist owns this patient before sending anything.
    setSent(true);
  };

  return (
    <TherapistLayout
      breadcrumb={['Care', 'Reports', `${report.patientName} · ${report.weekLabel}`]}
      headerAction={
        <div className="flex gap-2 shrink-0">
          <button
            type="button"
            className="inline-flex items-center gap-2 border border-gray-200 bg-white text-gray-700 text-sm font-semibold px-4 py-2.5 rounded-xl hover:border-gray-400 transition-colors"
          >
            <Download size={15} aria-hidden="true" /> PDF
          </button>
          <button
            type="button"
            onClick={handleApproveAndSend}
            disabled={sent}
            className="inline-flex items-center gap-2 bg-gray-900 text-white text-sm font-semibold px-4 py-2.5 rounded-xl hover:bg-gray-800 disabled:opacity-50 transition-colors"
          >
            <Send size={15} aria-hidden="true" /> {sent ? 'Sent' : `Share to ${report.patientName.split(' ')[0]}`}
          </button>
        </div>
      }
    >
      <p className="text-xs font-semibold tracking-widest text-gray-500 uppercase mb-2">
        Weekly report · {report.weekRange}
      </p>
      <h1 className="text-5xl font-black text-gray-900 mb-2">
        {report.patientName.split(' ')[0]}, <span className="italic font-serif font-normal">at a glance.</span>
      </h1>
      <p className="text-gray-500 mb-8">
        Generated by Aida on {report.generatedDate} · review, add a note, then share back to{' '}
        {report.patientName.split(' ')[0]}.
      </p>

      {/* Stat cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
        {report.stats.map((stat) => (
          <div key={stat.label} className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <p className="text-xs font-semibold tracking-widest text-gray-500 uppercase mb-2">{stat.label}</p>
            <p className="text-3xl font-black text-gray-900">
              {stat.value}{' '}
              {stat.delta && (
                <span className={`text-base font-bold ${stat.deltaPositive !== false ? 'text-emerald-700' : 'text-red-600'}`}>
                  {stat.delta}
                </span>
              )}
            </p>
            <p className="text-xs text-gray-500 mt-1">{stat.meta}</p>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        {/* Main column */}
        <div className="xl:col-span-2 space-y-6">
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <p className="text-xs font-semibold tracking-widest text-gray-500 uppercase mb-1">What moved</p>
            <h2 className="text-2xl font-black text-gray-900 mb-3">{report.summaryTitle}</h2>
            <p className="text-gray-600 leading-relaxed mb-6">{report.summaryText}</p>

            <p className="text-xs font-semibold tracking-widest text-gray-500 uppercase mb-3">Mood · Daily</p>
            <div style={{ height: 220 }}>
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={moodChartData} margin={{ top: 20, right: 10, bottom: 0, left: 10 }}>
                  <XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fontSize: 12, fill: '#9ca3af' }} />
                  <Tooltip
                    formatter={(value: number) => [value, 'Mood']}
                    contentStyle={{ borderRadius: 8, border: '1px solid #e5e7eb', fontSize: 12 }}
                  />
                  <Line
                    type="monotone"
                    dataKey="value"
                    stroke="#166534"
                    strokeWidth={2}
                    dot={{ r: 4, fill: '#166534' }}
                    label={{ position: 'top', fontSize: 12, fill: '#1a1a1a', fontWeight: 700 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>

            <p className="text-xs font-semibold tracking-widest text-gray-500 uppercase mt-6 mb-3">
              Sensor patterns · Body
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {report.sensorPatterns.map((pattern) => (
                <div key={pattern.label} className="border border-gray-100 rounded-xl p-4">
                  <p className="text-[11px] font-semibold tracking-widest text-gray-500 uppercase mb-2">
                    {pattern.label}
                  </p>
                  <p className="text-lg font-black text-gray-900 mb-2">{pattern.value}</p>
                  <Sparkline data={pattern.trend} color={pattern.color} height={28} />
                  <p className="text-xs text-gray-500 mt-2">{pattern.meta}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right column */}
        <div className="space-y-6">
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <p className="text-xs font-semibold tracking-widest text-gray-500 uppercase mb-4">Key insights · Aida</p>
            <ul className="space-y-4">
              {report.keyInsights.map((insight) => (
                <li key={insight.id} className={`border-l-4 pl-4 ${INSIGHT_STYLES[insight.tone]}`}>
                  <p className="font-bold text-gray-900 text-sm mb-1">{insight.title}</p>
                  <p className="text-xs text-gray-500 leading-relaxed">{insight.description}</p>
                </li>
              ))}
            </ul>
          </div>

          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <p className="text-xs font-semibold tracking-widest text-gray-500 uppercase mb-4">
              Your note to {report.patientName.split(' ')[0]}
            </p>
            {editingNote ? (
              <textarea
                value={note}
                onChange={(e) => setNote(e.target.value.slice(0, MAX_LENGTHS.longText))}
                maxLength={MAX_LENGTHS.longText}
                rows={5}
                autoFocus
                onBlur={() => setNote(sanitizeText(note))}
                className="w-full px-3 py-2.5 text-sm border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-gray-900 bg-gray-50 resize-none mb-4"
              />
            ) : (
              <div className="bg-[#F5F0E8] rounded-xl p-4 mb-4">
                <p className="text-sm text-gray-700 italic leading-relaxed">&ldquo;{note}&rdquo;</p>
              </div>
            )}
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setEditingNote((v) => !v)}
                className="inline-flex items-center gap-1.5 border border-gray-200 text-gray-700 text-sm font-semibold px-4 py-2.5 rounded-xl hover:border-gray-400"
              >
                <Pencil size={13} aria-hidden="true" /> {editingNote ? 'Done' : 'Edit'}
              </button>
              <button
                type="button"
                onClick={handleApproveAndSend}
                disabled={sent}
                className="ml-auto inline-flex items-center gap-2 bg-gray-900 text-white text-sm font-semibold px-4 py-2.5 rounded-xl hover:bg-gray-800 disabled:opacity-50 transition-colors"
              >
                {sent ? 'Sent ✓' : 'Approve & send'}
              </button>
            </div>
          </div>

          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
            <p className="text-xs font-semibold tracking-widest text-gray-500 uppercase mb-3">Also in this report</p>
            <p className="text-sm text-gray-500 leading-relaxed">
              Full session transcript summaries and care-plan compliance detail are available on the{' '}
              <span className="font-semibold text-gray-700">Care plans</span> and{' '}
              <span className="font-semibold text-gray-700">Patient detail</span> pages for{' '}
              {report.patientName.split(' ')[0]}.
            </p>
          </div>
        </div>
      </div>
    </TherapistLayout>
  );
};

export default WeeklyReportPage;