# Generated by Django 6.1.1 on 2026-10-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide it from the app immediately.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(max_length=500)),
                ("author", models.CharField(blank=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hope", "Hope"),
                            ("resilience", "Resilience"),
                            ("calm", "Calm"),
                            ("self_care", "Self-care"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "category"],
                        name="motivation__is_acti_c0c2ba_idx",
                    )
                ],
            },
        ),
    ]
