# Generated by Django 6.1.1 on 2026-10-10 14:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("motivation", "0002_seed_quotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=core.fields.PersonNameField(
                blank=True, label="Author", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="text",
            field=core.fields.FreeTextField(
                label="Quote", min_length=10, rule_max_length=500
            ),
        ),
    ]
