# Generated by Django 6.1.1 on 2026-10-10 14:09

import core.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference", "0003_city_is_verified_and_turkiye"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=core.fields.PersonNameField(label="City", max_length=120),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                max_length=2,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a two-letter ISO country code, e.g. PK.",
                        regex="^[A-Z]{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=core.fields.OrganisationNameField(
                label="Name", max_length=100, rule_max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                max_length=2,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a two-letter ISO 639-1 code, e.g. ur.",
                        regex="^[a-z]{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=core.fields.OrganisationNameField(
                label="Name", max_length=100, rule_max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="name",
            field=core.fields.OrganisationNameField(
                label="Name", max_length=100, rule_max_length=100
            ),
        ),
    ]
