# Generated by Django 6.1.1 on 2026-10-10 14:09

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_last_active_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=core.fields.PersonNameField(label="Full name", max_length=255),
        ),
    ]
