# Generated by Django 6.1.1 on 2026-10-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_id", models.BigIntegerField(null=True)),
                ("actor_role", models.CharField(max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("download", "Download"),
                            ("identity_reveal", "Identity reveal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("patient_identity", "Patient identity"),
                            ("mental_health_history", "Mental health history"),
                            ("credential_document", "Credential document"),
                            ("report_description", "Report description"),
                        ],
                        max_length=40,
                    ),
                ),
                ("resource_id", models.CharField(blank=True, max_length=64)),
                ("patient_user_id", models.BigIntegerField(null=True)),
                ("ip", models.GenericIPAddressField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["patient_user_id", "created_at"],
                        name="audit_acces_patient_84b82b_idx",
                    ),
                    models.Index(
                        fields=["actor_id", "created_at"],
                        name="audit_acces_actor_i_e7df8f_idx",
                    ),
                ],
            },
        ),
    ]
