# Generated by Django 6.1.1 on 2026-10-10 14:09

import core.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psychologists", "0002_psychologistprofile_is_accepting_patients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psychologistprofile",
            name="bio",
            field=core.fields.FreeTextField(
                blank=True, default="", label="Bio", min_length=30, rule_max_length=2000
            ),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="license_issuing_authority",
            field=core.fields.OrganisationNameField(
                label="Issuing authority", max_length=200, rule_max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="license_number",
            field=core.fields.IdentifierField(label="License number", max_length=64),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="qualifications",
            field=core.fields.FreeTextField(
                label="Qualifications", min_length=10, rule_max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0,
                        message="Years of experience must be a whole number between 0 and 60.",
                    ),
                    django.core.validators.MaxValueValidator(
                        60,
                        message="Years of experience must be a whole number between 0 and 60.",
                    ),
                ]
            ),
        ),
    ]
