# Generated by Django 6.1.1 on 2026-10-11 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psychologists", "0003_alter_psychologistprofile_bio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("license", "License"),
                            ("degree", "Degree certificate"),
                            ("other", "Other credential"),
                        ],
                        max_length=20,
                    ),
                ),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                ("file_type", models.CharField(max_length=10)),
                ("size", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="psychologists.psychologistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at", "id"],
            },
        ),
    ]
